"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var map_1 = require("./directives/map");
exports.AgmMap = map_1.AgmMap;
var circle_1 = require("./directives/circle");
exports.AgmCircle = circle_1.AgmCircle;
var info_window_1 = require("./directives/info-window");
exports.AgmInfoWindow = info_window_1.AgmInfoWindow;
var kml_layer_1 = require("./directives/kml-layer");
exports.AgmKmlLayer = kml_layer_1.AgmKmlLayer;
var data_layer_1 = require("./directives/data-layer");
exports.AgmDataLayer = data_layer_1.AgmDataLayer;
var marker_1 = require("./directives/marker");
exports.AgmMarker = marker_1.AgmMarker;
var polygon_1 = require("./directives/polygon");
exports.AgmPolygon = polygon_1.AgmPolygon;
var polyline_1 = require("./directives/polyline");
exports.AgmPolyline = polyline_1.AgmPolyline;
var polyline_point_1 = require("./directives/polyline-point");
exports.AgmPolylinePoint = polyline_point_1.AgmPolylinePoint;
//# sourceMappingURL=directives.js.map