/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
import * as import0 from '@angular/core';
import * as import1 from '../../../../src/core/directives/info-window';
export declare const RenderType_AgmInfoWindow: import0.RendererType2;
export declare function View_AgmInfoWindow_0(l: any): import0.ɵViewDefinition;
export declare const AgmInfoWindowNgFactory: import0.ComponentFactory<import1.AgmInfoWindow>;
