/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
import * as import0 from '@angular/core';
import * as import3 from '../../../../src/core/directives/map';
export declare const RenderType_AgmMap: import0.RendererType2;
export declare function View_AgmMap_0(l: any): import0.ɵViewDefinition;
export declare const AgmMapNgFactory: import0.ComponentFactory<import3.AgmMap>;
